### ISSUE TITLE
Zlib

### ISSUE THREAD

**Issue by MiyanoOsu** [nfriedly/miyoo-toolchain#1]
Your toolchain lack zlib, i compile game and it said "underfined reference to symbol 'gzseek' "

**Comment by MiyanoOsu** [comment]
> Your toolchain lack zlib, i compile game and it said "underfined reference to symbol 'gzseek' "

I search on internet and add -lz in makefile, now it run fine ._.

**Comment by nfriedly** [comment]
Hey, sorry, this needs some work.... I didn't quite understand when I was putting it together that all of the branches are currently using the older tool chain, nothing is using the newer musl one :/

However, if you're trying to build for miyoo cfw 1.3.3, then this is the correct tool chain, and should work for you.
